# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Edible' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Edible

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'AlamofireImage', '~> 3.3'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'


  target 'EdibleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EdibleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

